#!/bin/sh

set -e

line=$(grep "base " /etc/libnss-ldap.conf)
basedn=$(echo $line | cut -d' ' -f2)
sudoers_base="sudoers_base ou=Roles,"$basedn
base="BASE "$basedn

line=$(grep "host " /etc/libnss-ldap.conf)
host=$(echo $line | cut -d' ' -f2)
uri="URI ldap://"$host":389"
#echo $uri

sed -i '/BASE /c\' /etc/sudo-ldap.conf
sed -i '/sudoers_base /c\' /etc/sudo-ldap.conf
sed -i '/URI /c\' /etc/sudo-ldap.conf

printf "$sudoers_base\n" | tee -a /etc/sudo-ldap.conf
printf "$base\n" | tee -a /etc/sudo-ldap.conf
printf "$uri\n" | tee -a /etc/sudo-ldap.conf

